USE OlistDB;
GO
 
CREATE SCHEMA stg;
GO
 
ALTER SCHEMA stg TRANSFER dbo.Customers;
ALTER SCHEMA stg TRANSFER dbo.Orders;
ALTER SCHEMA stg TRANSFER dbo.OrderItem;
ALTER SCHEMA stg TRANSFER dbo.OrderPayment;
ALTER SCHEMA stg TRANSFER dbo.OrderReview;
ALTER SCHEMA stg TRANSFER dbo.Products;
ALTER SCHEMA stg TRANSFER dbo.Seller;
ALTER SCHEMA stg TRANSFER dbo.Geolocation;
ALTER SCHEMA stg TRANSFER dbo.ProductTranslation;
GO
 
-- Sanity check 
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'stg'
ORDER BY TABLE_NAME;
GO
 